name    'adamcrews-nessus'
version '0.2.0'
source 'git://github.com/adamcrews/puppet-nessus'
author 'Adam Crews'
license 'Apache License, Version 2.0'
summary 'Nessus Module'
description 'Nessus Module to manage the Nessus Vulnerability scanner.'
project_page 'https://github.com/adamcrews/puppet-nessus'
dependency 'puppetlabs/stdlib', '>= 3.2.1'
